---
title: "umetal_asd"
author: "John Dou"
date: "February 28, 2020"
output: html_document
---

```{r load}
library(sas7bdat)
library(openxlsx)
library(dplyr)
library(ggplot2)
library(ggplot2)
library(ggrepel)
library(corrplot)
library(logbin)
library(epitools)
path <- 'F:/Drive/Urine_Metals/Urine-Metals-ASD'
```

# Load data files
```{r load}
urine.metals <- readRDS(file=file.path(path,'Data/urine_metals.RDS'))
spec.grav <- readRDS(file=file.path(path,'Data/spgrav.rds'))
marbearl <- read.sas7bdat(file=file.path(path,'Data/e_m_covars_v5_20191115.sas7bdat'))
marb.cov <- read.sas7bdat(file=file.path(path,'Data/marbles_allcov_09mar20.sas7bdat'))

metals <- unique(urine.metals$Analyte.Code)
metals <- as.list(metals)
names(metals) <- unlist(metals)
```

# Specific gravity adjustment
```{r spec grav}
#check to make sure IDs are all present
table(spec.grav$SID %in% urine.metals$SID)
table(urine.metals$SID %in% spec.grav$SID)


#histogram of specific gravities
spec.grav$cohort <- urine.metals[match(spec.grav$SID, urine.metals$SID), 'cohort']
ggplot(spec.grav, aes(x=Concentration, fill=cohort)) +
  geom_histogram()




sg_ref <- median(spec.grav$Concentration, na.rm=TRUE)

urine.metals$sg <- spec.grav[match(urine.metals$SID, spec.grav$SID), 'Concentration']

#impute values if < LOD
urine.metals$Concentration_sg <- ifelse(urine.metals$Concentration < urine.metals$LOD,
                                        urine.metals$LOD/sqrt(2), urine.metals$Concentration)

#adjust for specific gravity
urine.metals$Concentration_sg <- urine.metals$Concentration_sg * (sg_ref - 1)/(urine.metals$sg - 1)

urine.Zscore <- urine.metals %>% 
  group_by(Analyte.Code) %>%
  mutate(Z=(Concentration_sg-mean(Concentration_sg, na.rm=T))/sd(Concentration_sg, na.rm=T)) %>%
  data.frame
urine.Zscore$Concentration_sg <- ifelse(urine.Zscore$Z>3, NA, urine.Zscore$Concentration_sg)
```


```{r}
#histograms of distribution
pdf(file.path(path,'Plots/urine_metals_distributions_sg.pdf'))
for(metal in metals){
  sub <- urine.Zscore %>% filter(Analyte.Code==metal)
  p1 <- ggplot(sub, aes(x=Concentration_sg, fill=cohort)) +
    geom_histogram(alpha=0.6, position='identity') +
    theme_bw() +
    ggtitle(metal)
  print(p1)
}
dev.off()
```


# Merge in ASD data and remove multiple births
```{r dx_alg}
table(urine.Zscore$fam %in% marbearl$famid) #all T

marbearl.metal <- marbearl[marbearl$famid %in% urine.Zscore$fam, ]

multiple <- marbearl.metal[duplicated(marbearl.metal$famid) | duplicated(marbearl.metal$famid, fromLast=T),]
multiple[multiple$project=='EARLI',c('coi_id','famid','n_pregs','Dx_alg','BirthMonth','BirthYear')]
#      coi_id famid n_pregs Dx_alg BirthMonth BirthYear
# 405 9002602 90026       8      0          1      2010   300004, 3030048
# 406 9002607 90026       8      0          1      2010

# 424 9004706 90047       2      0          8      2010   4010030, 4030050
# 425 9004707 90047       2      1          8      2010

# 560 9020203 90202       2      2         11      2011   2030222
# 561 9020204 90202       2      2         11      2011

# 565 9020604 90206       1      2         11      2011   4030124
# 566 9020605 90206       1      1         11      2011

# 602 9025402 90254       1      0          6      2012   4020262, 4030148
# 603 9025405 90254       1      0          6      2012

# 618 9031302 90313       2      1          7      2012   3030233, 2030284
# 619 9031305 90313       2      1          7      2012

# 625 9031902 90319       4      1          8      2012   1030225, 1030271
# 626 9031905 90319       4      1          8      2012



multiple[multiple$project=='MARBLES',c('project','coi_id','famid','n_pregs','Dx_alg','BirthMonth','BirthYear')]
#     project coi_id famid n_pregs Dx_alg BirthMonth BirthYear
# 2   MARBLES 500204  5002       2      0          3      2007 sep births
# 3   MARBLES 500207  5002       3      0          3      2010 sep births
# 4   MARBLES 500208  5002       4      1          5      2011 sep births

# 9   MARBLES 501206  5012       4      0          5      2007 -
# 10  MARBLES 501207  5012       5      0         11      2008 only from this preg
# 11  MARBLES 501208  5012       6      0          4      2010 -

# 29  MARBLES 503505  5035       5      0          8      2008 sep births
# 30  MARBLES 503506  5035       6      0          1      2010 sep births

# 42  MARBLES 505305  5053       6      0         11      2008 sep births
# 43  MARBLES 505306  5053       9      0          2      2012 sep births

# 44  MARBLES 505504  5055       6      0         12      2007 -
# 45  MARBLES 505505  5055     NaN      1          4      2011 only fom this preg

# 53  MARBLES 506508  5065       3      0         11      2008 multiple birth (assigned to this)
# 54  MARBLES 506509  5065       3      0         11      2008 multiple birth

# 69  MARBLES 509705  5097       6      0          8      2008 multiple birth (assigned to this)
# 70  MARBLES 509706  5097       6      0          8      2008 multiple brith

# 85  MARBLES 512207  5122       4      0          1      2009 sep births
# 86  MARBLES 512208  5122       5      0          2      2011 sep births

# 90  MARBLES 513104  5131       1      0         12      2008 sep births
# 91  MARBLES 513105  5131       2      0          7      2012 sep births

# 95  MARBLES 513706  5137       2      0         10      2010 sep briths
# 96  MARBLES 513707  5137       3      0          1      2013 sep briths

# 107 MARBLES 515306  5153       8      0         12      2010 sep births
# 108 MARBLES 515308  5153      10      1          1      2013 sep briths

# 113 MARBLES 515805  5158       5    NaN          9      2009 sep briths
# 114 MARBLES 515807  5158       6      0          7      2011 sep briths

# 123 MARBLES 517404  5174       3      0          8      2009 multiple birth (assigned to this)
# 124 MARBLES 517405  5174       3      1          8      2009 multiple brith

# 141 MARBLES 519904  5199       1      2         11      2013 only from this preg
# 142 MARBLES 519905  5199       2    NaN          6      2017 -

# 165 MARBLES 525003  5250       0      0          3      2011 sep births
# 166 MARBLES 525004  5250       1      2          2      2013 sep births

# 167 MARBLES 525105  5251       2      1         10      2010 sep births
# 168 MARBLES 525106  5251       3      1          7      2013 sep births

# 174 MARBLES 526004  5260       2      2          8      2011 only from this preg
# 175 MARBLES 526005  5260       4    NaN          8      2016 -

# 179 MARBLES 527307  5273       5      2          9      2013 only from this preg
# 180 MARBLES 527308  5273       7    NaN         11      2018 -

# 185 MARBLES 528104  5281       3      1          2      2012 sep births
# 186 MARBLES 528105  5281       4      2          6      2013 sep births
# 187 MARBLES 528106  5281       5    NaN          8      2016 -

# 189 MARBLES 528304  5283     NaN      1          2      2012 only from this preg
# 190 MARBLES 528306  5283       3      1          2      2016 -

# 211 MARBLES 533104  5331       3      1          8      2013 sep births
# 212 MARBLES 533106  5331       4      2         11      2014 sep births

# 220 MARBLES 534104  5341       2      1          8      2013 only from this preg
# 221 MARBLES 534106  5341       3    NaN          4      2017 -

# 231 MARBLES 535904  5359       2      1          8      2013 sep births
# 232 MARBLES 535906  5359       3      1          6      2015 sep births

# 234 MARBLES 536104  5361       3      1          4      2014 only from this preg
# 235 MARBLES 536107  5361       4    NaN          3      2017 -

# 250 MARBLES 538904  5389       2      1         11      2014 multiple birth (assigned this one)
# 251 MARBLES 538905  5389       2      1         11      2014 multiple birth

# 255 MARBLES 539604  5396       3      0          4      2014 only from this preg
# 256 MARBLES 539607  5396       4    NaN          5      2016 -

# 293 MARBLES 545504  5455       1      0          6      2015 multiple birth (assigned this one)
# 294 MARBLES 545505  5455       1      2          6      2015 multiple birth

# 301 MARBLES 546404  5464      12      1          5      2015 only from this preg
# 302 MARBLES 546408  5464      13    NaN          4      2017 -

multiple.marb <- marbearl[marbearl$coi_id %in% urine.metals$child_id, ]
multiple.marb <- multiple.marb[duplicated(multiple.marb$famid) | duplicated(multiple.marb$famid, fromLast=T), ]
multiple.marb[multiple.marb$project=='MARBLES',c('project','coi_id','famid','n_pregs','Dx_alg','BirthMonth','BirthYear')]
#     project coi_id famid n_pregs Dx_alg BirthMonth BirthYear
# 2   MARBLES 500204  5002       2      0          3      2007
# 3   MARBLES 500207  5002       3      0          3      2010
# 4   MARBLES 500208  5002       4      1          5      2011
# 29  MARBLES 503505  5035       5      0          8      2008
# 30  MARBLES 503506  5035       6      0          1      2010
# 42  MARBLES 505305  5053       6      0         11      2008
# 43  MARBLES 505306  5053       9      0          2      2012
# 85  MARBLES 512207  5122       4      0          1      2009
# 86  MARBLES 512208  5122       5      0          2      2011
# 90  MARBLES 513104  5131       1      0         12      2008
# 91  MARBLES 513105  5131       2      0          7      2012
# 95  MARBLES 513706  5137       2      0         10      2010
# 96  MARBLES 513707  5137       3      0          1      2013
# 107 MARBLES 515306  5153       8      0         12      2010
# 108 MARBLES 515308  5153      10      1          1      2013
# 113 MARBLES 515805  5158       5    NaN          9      2009
# 114 MARBLES 515807  5158       6      0          7      2011
# 165 MARBLES 525003  5250       0      0          3      2011
# 166 MARBLES 525004  5250       1      2          2      2013
# 167 MARBLES 525105  5251       2      1         10      2010
# 168 MARBLES 525106  5251       3      1          7      2013
# 185 MARBLES 528104  5281       3      1          2      2012
# 186 MARBLES 528105  5281       4      2          6      2013
# 211 MARBLES 533104  5331       3      1          8      2013
# 212 MARBLES 533106  5331       4      2         11      2014
# 231 MARBLES 535904  5359       2      1          8      2013
# 232 MARBLES 535906  5359       3      1          6      2015


#marbles diag first
urine.Zscore$asd <- ifelse(urine.Zscore$cohort=='MARBLES',marbearl.metal[match(urine.Zscore$child_id, marbearl.metal$coi_id),'Dx_alg'] , NA)

urine.marbles <- urine.Zscore[urine.Zscore$cohort=='MARBLES',]


#no multiples birhts
multi.birth.m <- multiple[multiple$project=='MARBLES',c('project','coi_id','famid','n_pregs','Dx_alg','BirthMonth','BirthYear')] %>%
  group_by(famid) %>% filter(min(n_pregs) == max(n_pregs))
multi.birth.e <- multiple[multiple$project=='EARLI',c('coi_id','famid','n_pregs','Dx_alg','BirthMonth','BirthYear')] %>%
  group_by(famid) %>% filter(min(n_pregs) == max(n_pregs))

multi.birth <- c(unique(as.character(multi.birth.m$famid)), unique(as.character(multi.birth.e$famid)))


marbearl.metal <- marbearl.metal[!marbearl.metal$famid %in% multi.birth,]

urine.nomulti <- urine.Zscore[!urine.Zscore$fam %in% multi.birth, ]

urine.nomulti$asd <- ifelse(urine.nomulti$cohort=='EARLI',marbearl.metal[match(urine.nomulti$fam, marbearl.metal$famid),'Dx_alg'] , urine.nomulti$asd)

urine.nomulti <- urine.nomulti[!duplicated(paste0(urine.nomulti$SID,urine.nomulti$Analyte.Code)),]

#LOD descriptives by ASD
metals.asd <- urine.nomulti %>% group_by(Analyte.Code, asd) %>% 
  summarize(mean=mean(Concentration), sd=sd(Concentration), above_lod=sum(Concentration>LOD), n=n(), pct_over_LOD=round(above_lod/n*100,1)) %>%
  data.frame()

write.csv(metals.asd, file=file.path(path,'Tables/asd_metals.csv'), row.names = F)
```


# EARLI

```{r metal_asd}
urine.earli <- urine.nomulti[urine.nomulti$cohort=='EARLI',]
urine.earli$Con_sg_orig <- urine.earli$Concentration_sg
urine.earli <- urine.earli %>% group_by(Analyte.Code) %>%
  mutate(Z=(Concentration_sg-mean(Concentration_sg, na.rm=T))/sd(Concentration_sg, na.rm=T)) %>% data.frame
urine.earli$Concentration_sg <- ifelse(urine.earli$Z>5, NA, urine.earli$Concentration_sg)


### split into timepoints
urine.earliT1 <- urine.earli[urine.earli$Time=='T1',]
urine.earliT2 <- urine.earli[urine.earli$Time=='T2',]
urine.earliT3 <- urine.earli[urine.earli$Time=='T3',]

earli.counting <- data.frame(fam=unique(urine.earli$fam))
earli.counting$T1 <- earli.counting$fam %in% urine.earliT1$fam
earli.counting$T2 <- earli.counting$fam %in% urine.earliT2$fam
earli.counting$T3 <- earli.counting$fam %in% urine.earliT3$fam
earli.counting$N_samp <- earli.counting$T1 + earli.counting$T2 + earli.counting$T3
table(earli.counting$N_samp)

table(urine.earliT1$Z>3, urine.earliT1$Analyte.Code)
table(urine.earliT1$Concentration<=0, urine.earliT1$Analyte.Code)

### get earliest measure
fams <- unique(urine.earli$fam)

pick <- lapply(fams, FUN=function(fam){
  if(fam %in% urine.earliT1$fam){
    urine.earliT1[urine.earliT1$fam==fam,]
  }else if(fam %in% urine.earliT2$fam){
    urine.earliT2[urine.earliT2$fam==fam,]
  }else{
    urine.earliT3[urine.earliT3$fam==fam,]
  }
})

pick.last <- lapply(fams, FUN=function(fam){
  if(fam %in% urine.earliT3$fam){
    urine.earliT3[urine.earliT3$fam==fam,]
  }else if(fam %in% urine.earliT2$fam){
    urine.earliT2[urine.earliT2$fam==fam,]
  }else{
    urine.earliT1[urine.earliT1$fam==fam,]
  }
})

metals.earli <- do.call(rbind, pick)
metals.earli.last <- do.call(rbind, pick.last)

### separate those with only one sample
onlyone.earli <- earli.counting[earli.counting$N_samp==1,]
onlyone.earli.early <- onlyone.earli[!onlyone.earli$T3,]
onlyone.earli.late <- onlyone.earli[onlyone.earli$T3,]

metals.earli <- metals.earli[!metals.earli$fam %in% onlyone.earli.late$fam, ]
metals.earli.last <- metals.earli.last[!metals.earli.last$fam %in% onlyone.earli.early$fam, ]


ecount.first <- metals.earli %>% filter(Analyte.Code=='Lead')
ecount.last <- metals.earli.last %>% filter(Analyte.Code=='Lead')
table(ecount.first$SID %in% ecount.last$SID)
table(ecount.first$child_id %in% ecount.last$child_id)
table(ecount.last$child_id %in% ecount.first$child_id)
```

```{r earli pc corr}
# get wide data set
concentrations.earli <- lapply(metals, FUN=function(x){
  values <- metals.earli %>% filter(Analyte.Code==x)
  concentrations <- values$Con_sg_orig
  names(concentrations) <- values$fam
  concentrations
})
concentrations.earli.last <- lapply(metals, FUN=function(x){
  values <- metals.earli.last %>% filter(Analyte.Code==x)
  concentrations <- values$Con_sg_orig
  names(concentrations) <- values$fam
  concentrations
})

wide.earli <- do.call(cbind.data.frame, concentrations.earli)
wide.earli <- wide.earli[,!colnames(wide.earli) %in% c('Beryllium','Platinum','Tungsten','Uranium','Vanadium')]
rownames(wide.earli) <- names(concentrations.earli[[1]])

wide.earli.last <- do.call(cbind.data.frame, concentrations.earli.last)
wide.earli.last <- wide.earli.last[,!colnames(wide.earli.last) %in% c('Beryllium','Platinum','Tungsten','Uranium','Vanadium')]
rownames(wide.earli.last) <- names(concentrations.earli.last[[1]])

### PCs

#first
wide.earli <- na.omit(wide.earli)
wide.earli <- apply(wide.earli, 2, FUN=function(x){
  m <- mean(x)
  sd <- sd(x)
  (x - m)/sd
})
pc.earli <- prcomp(wide.earli)
pcv.earli <- pc.earli$x

earli.first.scree <- data.frame(t(summary(pc.earli)$importance))
earli.first.scree$PC <- factor(rownames(earli.first.scree), levels=rownames(earli.first.scree))
earli.first.scree$Proportion.of.Variance <- round(earli.first.scree$Proportion.of.Variance, 2)
ggplot(earli.first.scree, aes(x=PC, y=Standard.deviation)) +
  geom_col() + geom_text(aes(label=Proportion.of.Variance), position=position_dodge(width=0.8), vjust=-0.25) + theme_bw()

#last
wide.earli.last <- na.omit(wide.earli.last)
wide.earli.last <- apply(wide.earli.last, 2, FUN=function(x){
  m <- mean(x)
  sd <- sd(x)
  (x - m)/sd
})
pc.earli.last <- prcomp(wide.earli.last)
pcv.earli.last <- pc.earli.last$x

earli.last.scree <- data.frame(t(summary(pc.earli.last)$importance))
earli.last.scree$PC <- factor(rownames(earli.last.scree), levels=rownames(earli.last.scree))
earli.last.scree$Proportion.of.Variance <- round(earli.last.scree$Proportion.of.Variance, 2)
ggplot(earli.last.scree, aes(x=PC, y=Standard.deviation)) +
  geom_col() + geom_text(aes(label=Proportion.of.Variance), position=position_dodge(width=0.8), vjust=-0.25) + theme_bw()


#on the metals
pc.earli.metal <- prcomp(t(wide.earli))
pcv.earli.metal <- data.frame(pc.earli.metal$x)

earli.fm.scree <- data.frame(t(summary(pc.earli.metal)$importance))
earli.fm.scree$PC <- factor(rownames(earli.fm.scree), levels=rownames(earli.fm.scree))
earli.fm.scree$Proportion.of.Variance <- round(earli.fm.scree$Proportion.of.Variance, 2)
ggplot(earli.fm.scree, aes(x=PC, y=Standard.deviation)) +
  geom_col() + geom_text(aes(label=Proportion.of.Variance), position=position_dodge(width=0.8), vjust=-0.25) + theme_bw()


pc.earli.last.metal <- prcomp(t(wide.earli.last))
pcv.earli.last.metal <- data.frame(pc.earli.last.metal$x)
screeplot(pc.earli.last.metal)
```

```{r}
pdf(file.path(path,'Plots/metal_correlation_earliT_early.pdf'))
  ggplot(pcv.earli.metal, aes(x=PC1, y=PC2, label=c('Sb','As','Ba','Cd','Cs','Cr','Co','Cu','Pb','Mn','Hg','Mo','Ni','Se','Tl','Sn','Zn'))) +
    geom_point() +
    geom_text_repel() +
    theme_bw()
  
  ggplot(pcv.earli.last.metal, aes(x=PC1, y=PC2, label=c('Sb','As','Ba','Cd','Cs','Cr','Co','Cu','Pb','Mn','Hg','Mo','Ni','Se','Tl','Sn','Zn'))) +
    geom_point() +
    geom_text_repel() +
    theme_bw()
dev.off()

pc.mat <- matrix(0, ncol=ncol(wide.earli), nrow=ncol(pcv.earli))
colnames(pc.mat) <- colnames(wide.earli)
rownames(pc.mat) <- colnames(pcv.earli)

for(met in colnames(wide.earli)){
  for(pc in colnames(pcv.earli)){
    pc.mat[pc, met] <- cor(wide.earli[,met], pcv.earli[,pc])
  }
}

library(reshape2)
pc.mat.long <- melt(pc.mat)
names(pc.mat.long) <- c('PC','Metal','Correlation')
pc.mat.long$PC <- gsub('Comp.','PC',pc.mat.long$PC)
pc.mat.long$PC <- factor(pc.mat.long$PC, levels=pc.mat.long$PC[1:17])

ggplot(pc.mat.long, aes(PC, Metal)) +
  geom_tile(aes(fill=Correlation)) +
  scale_fill_gradient2(low='blue', mid='white', high='red') +
  theme(axis.text.x=element_text(angle=90)) +
  xlab('')


# calculate cors
M.e <- cor(wide.earli, method='spearman', use='pairwise.complete.obs')
Ml.e <- cor(wide.earli.last, method='spearman', use='pairwise.complete.obs')

pdf(file.path(path,'Plots/EARLI_metal_correlation.pdf'), height=14, width=14)
  corrplot(M.e, method='ellipse', type='upper', addCoef.col='black')
  corrplot(Ml.e, method='ellipse', type='upper', addCoef.col='black')
dev.off()
```

```{r EARLI descriptives}
### sample characteristics
earl.cov <- read.csv(paste0(path,"/Data Extraction Codebook 20150203_export_20150203_1422987480_wide_20150204_1423070501.csv"))

get_covars <- function(samps, pc){
  samples <- samps[,c('SID','fam','asd')] %>% unique()
  demo <- marbearl.metal[match(samples$fam, marbearl.metal$famid),]
  demo <- demo[,c('famid','coi_id','coi_gender','maternal_age','GA_deliv_wks','MomEdu','BSRC_group_Sib_36mos')]
  demo$MomEdu <- demo$MomEdu > 3 #college degree or not
  
  covs <- earl.cov[match(samples$fam, earl.cov$Family_ID),]
  covs2 <- marbearl[match(samples$fam, marbearl$famid),]
  
  pd <- merge(samps, demo, by.x='fam', by.y='famid', all.x=T)
  pd$asd <- pd$BSRC_group_Sib_36mos
  pd$asd <- factor(pd$asd, levels=c('TD','Non-TD','ASD'))
  pd$ever_smoke <- covs[match(pd$fam, covs$Family_ID), 'cigarettes_1']
  pd$reg_smoke <- covs[match(pd$fam, covs$Family_ID), 'regularly_2']
  pd$preg_smoke <- covs[match(pd$fam, covs$Family_ID), 'EARLI_HB_smoke']
  pd$PC1 <- pcv.earli[match(pd$fam, rownames(pc)),1]
  pd$PC2 <- pcv.earli[match(pd$fam, rownames(pc)),2]
  pd$site <- covs2$site
  
  pd
}

metals.earli.T2 <- get_covars(metals.earli, pcv.earli)
metals.earli.T3 <- get_covars(metals.earli.last, pcv.earli.last)

earli.T2.summ <- metals.earli.T2 %>% group_by(Analyte.Code) %>%
  summarize(mean=mean(Concentration_sg, na.rm=T), sd=sd(Concentration_sg, na.rm=T), median=median(Concentration_sg, na.rm=T),
            IQR=IQR(Concentration_sg, na.rm=T),  above_lod=sum(Concentration>LOD, na.rm=T), n=n(), pct_over_LOD=round(above_lod/n*100,1)) %>% data.frame()

earli.T3.summ <- metals.earli.T3 %>% group_by(Analyte.Code) %>%
  summarize(mean=mean(Concentration_sg, na.rm=T), sd=sd(Concentration_sg, na.rm=T), median=median(Concentration_sg, na.rm=T),
            IQR=IQR(Concentration_sg, na.rm=T), above_lod=sum(Concentration>LOD, na.rm=T), n=n(), pct_over_LOD=round(above_lod/n*100,1)) %>% data.frame()

rounding <- function(x){
  x$mean <- signif(x$mean, 3)
  x$sd <- signif(x$sd, 3)
  x$median <- signif(x$median, 3)
  x$IQR <- signif(x$IQR, 3)
  
  x
}


### descriptive tables
library(compareGroups)

gather_descriptives <- function(pd){
  descriptives <- pd[!duplicated(pd$fam),]
  descriptives <- descriptives[!is.na(descriptives$asd) & !is.na(descriptives$MomEdu &
                              !is.na(descriptives$coi_gender)) & !is.na(descriptives$maternal_age)
                              & !is.na(descriptives$GA_deliv_wks),]
  
  
  descriptives$MomEdu <- ifelse(descriptives$MomEdu, "College Degree", "No College Degree")
  descriptives$ever_smoke <- factor(descriptives$ever_smoke)
  descriptives$preg_smoke <- factor(descriptives$preg_smoke)
  
  restab <- compareGroups(asd ~ MomEdu + coi_gender + maternal_age + GA_deliv_wks + ever_smoke + preg_smoke,
                          data=descriptives)
  createTable(restab)
}

tab.earli.T2 <- gather_descriptives(metals.earli.T2)
tab.earli.T3 <- gather_descriptives(metals.earli.T3)

export2word(tab.earli.T2, file=file.path(path,'Tables/EARLI_early_table1.docx'))
export2word(tab.earli.T3, file=file.path(path,'Tables/EARLI_late_table1.docx'))


# ### covariate landscape relationships
# library(reshape2)
# covs <- c('asd','MomEdu','coi_gender','maternal_age','GA_deliv_wks','ever_smoke', 'preg_smoke')
# 
# cov_p <- function(pd){
#   cov.mat <- matrix(0, ncol=length(covs), nrow=length(metals))
#   colnames(cov.mat) <- covs
#   rownames(cov.mat) <- names(metals)
#   
#   for(met in metals){
#     sub <- pd %>% filter(Analyte.Code==met)
#     cov.mat[met, 'asd'] <- summary(aov(sub$Concentration_sg ~ sub$asd))[[1]]$`Pr(>F)`[1]
#     cov.mat[met, 'MomEdu'] <- t.test(sub$Concentration_sg~sub$MomEdu)$p.value
#     cov.mat[met, 'coi_gender'] <- t.test(sub$Concentration_sg~sub$coi_gender)$p.value
#     cov.mat[met, 'maternal_age'] <- summary(lm(sub$Concentration_sg~sub$maternal_age))$coefficients[2,4]
#     cov.mat[met, 'GA_deliv_wks'] <- summary(lm(sub$Concentration_sg~sub$GA_deliv_wks))$coefficients[2,4]
#     cov.mat[met, 'ever_smoke'] <- t.test(sub$Concentration_sg~sub$ever_smoke)$p.value
#     cov.mat[met, 'preg_smoke'] <- t.test(sub$Concentration_sg~sub$preg_smoke)$p.value
#   }
#   
#   colnames(cov.mat) <- c("ASD", "Mom Edu", "Sex", "Mom Age", "Gest Age", "Ever Smoke", "Preg Smoke")
#   
#   
#   cov.mat.long <- melt(cov.mat)
#   cov.mat.long$bin <- cut(cov.mat.long$value, breaks=c(0, 0.05, 0.1, 0.2, 0.5, 1.0))
#   ggplot(cov.mat.long, aes(x=Var2, y=Var1, fill=bin)) +
#     geom_tile() + 
#     theme_bw() + xlab("") + ylab("") + labs(fill='P') +
#     theme(axis.text.x = element_text(angle=-20)) +
#     scale_fill_manual(breaks=levels(cov.mat.long$bin),
#                       values=c("darkred","red","orange","yellow","white"))
# }
# 
# cov_p(metals.earli.T2)
# cov_p(metals.earli.T3)
# 
# 
# 
# #lead by west/east coast
# metals.earli.T2$coast <- ifelse(metals.earli.T2$site %in% c("Drexel", "Johns Hopkins University"),
#                                 'east',
#                                 'west')
# metals.earli.T3$coast <- ifelse(metals.earli.T3$site %in% c("Drexel", "Johns Hopkins University"),
#                                 'east',
#                                 'west')
# coast.pb.T2 <- metals.earli.T2 %>% filter(Analyte.Code=='Lead')
# coast.pb.T3 <- metals.earli.T3 %>% filter(Analyte.Code=='Lead')
# 
# table(coast.pb.T2$coast)
# ggplot(coast.pb.T2, aes(x=coast, y=Concentration_sg)) +
#   geom_violin() + geom_point(position='jitter')
# t.test(Concentration_sg~coast, data=coast.pb.T2)
# 
# table(coast.pb.T3$coast)
# ggplot(coast.pb.T3, aes(x=coast, y=Concentration_sg)) +
#   geom_violin() + geom_point(position='jitter')
# t.test(Concentration_sg~coast, data=coast.pb.T3)
# 
# table(coast.pb.T2$site)
# ggplot(coast.pb.T2, aes(x=site, y=Concentration_sg)) +
#   geom_violin() + geom_point(position='jitter')
# aov(Concentration_sg~site, data=coast.pb.T2) %>% summary
# 
# table(coast.pb.T3$site)
# ggplot(coast.pb.T3, aes(x=site, y=Concentration_sg)) +
#   geom_violin() + geom_point(position='jitter')
# aov(Concentration_sg~site, data=coast.pb.T3) %>% summary
# 
# ### PC vs ASD
# earli.pc_asd <- metals.earli.T2 %>% filter(Analyte.Code=='Lead')
# ggplot(earli.pc_asd, aes(x=PC1, y=PC2, col=asd)) +
#   geom_point() + theme_bw()
# glm(asd ~ PC1 + PC2, data=earli.pc_asd[earli.pc_asd$asd != 'Non-TD',], family=binomial(link="logit")) %>% summary


### bivariate tests
lod_percents <- read.csv(file.path(path,"../Metals QC/over_LOD_cohort.csv"))
lod.earli <- lod_percents[lod_percents$cohort=='EARLI',]
lod.earli$mod <- ifelse(lod.earli$pct_over_LOD>70, 'continuous', 'binary')
mod.type <- lod.earli$mod
names(mod.type) <- lod.earli$Analyte.Code

IQRs.T2 <- metals.earli.T2 %>% group_by(Analyte.Code) %>% summarize(IQR(Concentration_sg, na.rm=T)) %>% data.frame
IQRs.T2 <- IQRs.T2[,2]
names(IQRs.T2) <- metals

IQRs.T3 <- metals.earli.T3 %>% group_by(Analyte.Code) %>% summarize(IQR(Concentration_sg, na.rm=T)) %>% data.frame
IQRs.T3 <- IQRs.T3[,2]
names(IQRs.T3) <- metals

pdf(file.path(path,"Plots/earli_firstT_violin.pdf"))
for(met in metals){
  p1 = ggplot(metals.earli.T2 %>% filter(Analyte.Code==met), aes(x=factor(asd), y=Concentration_sg)) +
  geom_violin() +geom_jitter(shape=16, position=position_jitter(0.2)) +
    ggtitle(met) + xlab('') +
    theme_bw() +
    theme(axis.text.x=element_text(size=16, face="bold"))
  print(p1)
}
dev.off()

# pdf(file.path(path,"earli_firstT_voilin_smoke.pdf"))
# for(met in metals){
#   p2 = ggplot(metals.earli.T2 %>% filter(Analyte.Code==met), aes(x=factor(ever_smoke), y=Concentration_sg)) +
#   geom_violin() +geom_jitter(shape=16, position=position_jitter(0.2)) +
#     ggtitle(met) + xlab('') +
#     theme_bw() +
#     theme(axis.text.x=element_text(size=16, face="bold"))
#   print(p2)
# }
# dev.off()
```

Early vs Late Preg
```{r}
#remove ones with only single time
table(metals.earli$SID %in% metals.earli.last$SID)
only.one <- metals.earli$SID[metals.earli$SID %in% metals.earli.last$SID] %>% unique()

earli.epreg <- metals.earli[!metals.earli$SID %in% only.one, ]
earli.lpreg <- metals.earli.last[!metals.earli.last$SID %in% only.one, ]
dim(earli.epreg)
dim(earli.lpreg)
identical(earli.epreg$fam, earli.lpreg$fam)

length(unique(earli.epreg$fam))
length(unique(earli.lpreg$fam))


cor(earli.epreg$Con_sg_orig, earli.lpreg$Con_sg_orig)
time.cors <- sapply(metals, FUN=function(x){
  epreg = earli.epreg %>% filter(Analyte.Code==x)
  lpreg = earli.lpreg %>% filter(Analyte.Code==x)
  round(cor(epreg$Con_sg_orig, lpreg$Con_sg_orig, method='spearman'),2)
})
write.csv(time.cors, file.path(path,"earli_time_cor.csv"))

plot.tm <- function(met){
  m.epreg <- earli.epreg %>% filter(Analyte.Code==met)
  m.lpreg <- earli.lpreg %>% filter(Analyte.Code==met)
  dat <- data.frame(epreg=m.epreg$Con_sg_orig, lpreg=m.lpreg$Con_sg_orig)
  
  ggplot(dat, aes(epreg, lpreg)) +
    geom_point() +
    theme_bw() +
    xlab(paste0("Early Pregnancy ",met)) +
    ylab(paste0("Late Pregnancy ",met))
}

plot.tm('Lead')
plot.tm('Mercury')
plot.tm('Cadmium')
```

# MARBLES

```{r asd_metal_marb}
urine.marbles <- urine.nomulti[urine.nomulti$cohort=='MARBLES',]
urine.marbles$Con_sg_orig <- urine.marbles$Concentration_sg
urine.marbles <- urine.marbles %>% group_by(Analyte.Code) %>%
  mutate(Z=(Concentration_sg-mean(Concentration_sg, na.rm=T))/sd(Concentration_sg, na.rm=T)) %>% data.frame
urine.marbles$Concentration_sg <- ifelse(urine.marbles$Z>5, NA, urine.marbles$Concentration_sg)

urine.marbles <- urine.marbles[!is.na(urine.marbles$asd),]

### split into timepoints
urine.marblesT2 <- urine.marbles[urine.marbles$Time=='T2',]
urine.marblesT3 <- urine.marbles[urine.marbles$Time=='T3',]

marbles.counting <- data.frame(fam=unique(urine.marbles$fam))
marbles.counting$T2 <- marbles.counting$fam %in% urine.marblesT2$fam
marbles.counting$T3 <- marbles.counting$fam %in% urine.marblesT3$fam
marbles.counting$N_samp <- marbles.counting$T2 + marbles.counting$T3
table(marbles.counting$N_samp)


### pick earliest/latest measure
coi <- unique(urine.marbles$child_id)

pick <- lapply(coi, FUN=function(id){
  if(id %in% urine.marblesT2$child_id){
    urine.marblesT2[urine.marblesT2$child_id==id,]
  }else if(id %in% urine.marblesT3$child_id){
    urine.marblesT3[urine.marblesT3$child_id==id,]
  }
})

pick.last <- lapply(coi, FUN=function(id){
  if(id %in% urine.marblesT3$child_id){
    urine.marblesT3[urine.marblesT3$child_id==id,]
  }else if(id %in% urine.marblesT2$child_id){
    urine.marblesT2[urine.marblesT2$child_id==id,]
  }
})

metals.marbles <- do.call(rbind, pick)
metals.marbles.last <- do.call(rbind, pick.last)

### separate those with only one sample
onlyone.marbles <- marbles.counting[marbles.counting$N_samp==1,]
onlyone.marbles.early <- onlyone.marbles[!onlyone.marbles$T3,]
onlyone.marbles.late <- onlyone.marbles[onlyone.marbles$T3,]

metals.marbles <- metals.marbles[!metals.marbles$fam %in% onlyone.marbles.late$fam, ]
metals.marbles.last <- metals.marbles.last[!metals.marbles.last$fam %in% onlyone.marbles.early$fam, ]

```



```{r marbles pc corr}
# get wide data set
concentrations.marbles <- lapply(metals, FUN=function(x){
  values <- metals.marbles %>% filter(Analyte.Code==x)
  concentrations <- values$Con_sg_orig
  names(concentrations) <- values$child_id
  concentrations
})
concentrations.marbles.last <- lapply(metals, FUN=function(x){
  values <- metals.marbles.last  %>% filter(Analyte.Code==x)
  concentrations <- values$Con_sg_orig
  names(concentrations) <- values$child_id
  concentrations
})

wide.marbles <- do.call(cbind.data.frame, concentrations.marbles)
wide.marbles <- wide.marbles[,!colnames(wide.marbles) %in% c('Beryllium','Platinum','Tungsten','Uranium','Vanadium')]
rownames(wide.marbles) <- names(concentrations.marbles[[1]])

wide.marbles.last <- do.call(cbind.data.frame, concentrations.marbles.last)
wide.marbles.last <- wide.marbles.last[,!colnames(wide.marbles.last) %in% c('Beryllium','Platinum','Tungsten','Uranium','Vanadium')]
rownames(wide.marbles.last) <- names(concentrations.marbles.last[[1]])

### PCs

#first
wide.marbles <- na.omit(wide.marbles)
wide.marbles <- apply(wide.marbles, 2, FUN=function(x){
  m <- mean(x)
  sd <- sd(x)
  (x - m)/sd
})
pc.marbles <- prcomp(wide.marbles)
pcv.marbles <- pc.marbles$x

marbles.first.scree <- data.frame(t(summary(pc.marbles)$importance))
marbles.first.scree$PC <- factor(rownames(marbles.first.scree), levels=rownames(marbles.first.scree))
marbles.first.scree$Proportion.of.Variance <- round(marbles.first.scree$Proportion.of.Variance, 2)
ggplot(marbles.first.scree, aes(x=PC, y=Standard.deviation)) +
  geom_col() + geom_text(aes(label=Proportion.of.Variance), position=position_dodge(width=0.8), vjust=-0.25) + theme_bw()


#last
wide.marbles.last <- na.omit(wide.marbles.last)
wide.marbles.last <- apply(wide.marbles.last, 2, FUN=function(x){
  m <- mean(x)
  sd <- sd(x)
  (x - m)/sd
})
pc.marbles.last <- prcomp(wide.marbles.last)
pcv.marbles.last <- pc.marbles.last$x

marbles.last.scree <- data.frame(t(summary(pc.marbles.last)$importance))
marbles.last.scree$PC <- factor(rownames(marbles.last.scree), levels=rownames(marbles.last.scree))
marbles.last.scree$Proportion.of.Variance <- round(marbles.last.scree$Proportion.of.Variance, 2)
ggplot(marbles.last.scree, aes(x=PC, y=Standard.deviation)) +
  geom_col() + geom_text(aes(label=Proportion.of.Variance), position=position_dodge(width=0.8), vjust=-0.25) + theme_bw()



pc.marbles.metal <- prcomp(t(wide.marbles))
pcv.marbles.metal <- data.frame(pc.marbles.metal$x)

marbles.first.mscree <- data.frame(t(summary(pc.marbles.metal)$importance))
marbles.first.mscree$PC <- factor(rownames(marbles.first.mscree), levels=rownames(marbles.first.mscree))
marbles.first.mscree$Proportion.of.Variance <- round(marbles.first.mscree$Proportion.of.Variance, 2)
ggplot(marbles.first.mscree, aes(x=PC, y=Standard.deviation)) +
  geom_col() + geom_text(aes(label=Proportion.of.Variance), position=position_dodge(width=0.8), vjust=-0.25) + theme_bw()

pc.marbles.last.metal <- prcomp(t(wide.marbles.last))
pcv.marbles.last.metal <- data.frame(pc.marbles.last.metal$x)
screeplot(pc.marbles.last.metal)

pdf(file.path(path,'Plots/metal_correlation_marblesT_early.pdf'))
  ggplot(pcv.marbles.metal, aes(x=PC1, y=PC2, label=c('Sb','As','Ba','Cd','Cs','Cr','Co','Cu','Pb','Mn','Hg','Mo','Ni','Se','Tl','Sn','Zn'))) +
    geom_point() +
    geom_text_repel() +
    theme_bw()
  
  ggplot(pcv.marbles.last.metal, aes(x=PC1, y=PC2, label=c('Sb','As','Ba','Cd','Cs','Cr','Co','Cu','Pb','Mn','Hg','Mo','Ni','Se','Tl','Sn','Zn'))) +
    geom_point() +
    geom_text_repel() +
    theme_bw()
dev.off()



pc.mat <- matrix(0, ncol=ncol(wide.marbles), nrow=ncol(pcv.marbles))
colnames(pc.mat) <- colnames(wide.marbles)
rownames(pc.mat) <- colnames(pcv.marbles)

for(met in colnames(wide.marbles)){
  for(pc in colnames(pcv.marbles)){
    pc.mat[pc, met] <- cor(wide.marbles[,met], pcv.marbles[,pc])
  }
}

library(reshape2)
pc.mat.long <- melt(pc.mat)
names(pc.mat.long) <- c('PC','Metal','Correlation')
pc.mat.long$PC <- gsub('Comp.','PC',pc.mat.long$PC)
pc.mat.long$PC <- factor(pc.mat.long$PC, levels=pc.mat.long$PC[1:17])

ggplot(pc.mat.long, aes(PC, Metal)) +
  geom_tile(aes(fill=Correlation)) +
  scale_fill_gradient2(low='blue', mid='white', high='red') +
  theme(axis.text.x=element_text(angle=90)) +
  xlab('')


# calculate cors
M.m <- cor(wide.marbles, method='spearman', use='pairwise.complete.obs')
Ml.m <- cor(wide.marbles.last, method='spearman', use='pairwise.complete.obs')

pdf(file.path(path,'Plots/MARBLES_metal_correlation.pdf'), height=14, width=14)
  corrplot(M.m, method='ellipse', type='upper', addCoef.col='black')
  corrplot(Ml.m, method='ellipse', type='upper', addCoef.col='black')
dev.off()

M.both <- M.e
M.both[lower.tri(M.both)] <- M.m[lower.tri(M.m)]

Ml.both <- Ml.e
Ml.both[lower.tri(Ml.both)] <- Ml.m[lower.tri(Ml.m)]

colnames(M.both) <- c('Sb', 'As', 'Ba', 'Cd', 'Cs', 'Cr', 'Co', 'Cu', 'Pb', 'Mn', 'Hg', 'Mo', 'Ni', 'Se', 'Tl', 'Sn', 'Zn')
rownames(M.both) <- c('Sb', 'As', 'Ba', 'Cd', 'Cs', 'Cr', 'Co', 'Cu', 'Pb', 'Mn', 'Hg', 'Mo', 'Ni', 'Se', 'Tl', 'Sn', 'Zn')
colnames(Ml.both) <- c('Sb', 'As', 'Ba', 'Cd', 'Cs', 'Cr', 'Co', 'Cu', 'Pb', 'Mn', 'Hg', 'Mo', 'Ni', 'Se', 'Tl', 'Sn', 'Zn')
rownames(Ml.both) <- c('Sb', 'As', 'Ba', 'Cd', 'Cs', 'Cr', 'Co', 'Cu', 'Pb', 'Mn', 'Hg', 'Mo', 'Ni', 'Se', 'Tl', 'Sn', 'Zn')

pdf(file.path(path,'Plots/metal_correlation.pdf'), height=14, width=14)
  corrplot(M.both, method='ellipse', addCoef.col='black', diag=F, tl.pos='d', tl.col='red', cl.pos='b', cl.cex=1.3, number.cex=1.4, tl.cex=2.5)
  text(9, 18, "EARLI", cex=3)
  text(0, 8, "MARBLES", cex=3, srt=90)
  text(9, -1.8, "Spearman Correlation", cex=1.6)
  corrplot(Ml.both, method='ellipse', addCoef.col='black', diag=F, tl.pos='d', tl.col='red', cl.pos='b', cl.cex=1.3, number.cex=1.4, tl.cex=2.5)
  text(9, 18, "EARLI", cex=3)
  text(0, 8, "MARBLES", cex=3, srt=90)
  text(9, -1.8, "Spearman Correlation", cex=1.6)
dev.off()
```



```{r marbles descriptives}
### sample characteristics
get_covarsM <- function(samps, pc){
  samples <- samps[,c('SID','child_id','asd')] %>% unique()
  demo <- marbearl.metal[match(samples$child_id, marbearl.metal$coi_id),]
  demo <- demo[,c('famid','coi_id','coi_gender','maternal_age','GA_deliv_wks','MomEdu','BSRC_group_Sib_36mos')]
  demo$MomEdu <- demo$MomEdu > 3 #college degree or not
  
  marb.cov <- marb.cov[match(samples$child_id, marb.cov$COI_ID),]
  
  pd <- merge(samps, demo, by.x='child_id', by.y='coi_id', all.x=T)
  #pd$asd <- pd$BSRC_group_Sib_36mos
  pd$asd <- ifelse(pd$asd==0, 'TD',
                                 ifelse(pd$asd==1, 'ASD', 'Non-TD'))
  pd$asd <- factor(pd$asd, levels=c('TD','Non-TD','ASD'))
  pd$ever_smoke <- marb.cov[match(pd$child_id, marb.cov$COI_ID), 'MomEverSmoked']
  pd$reg_smoke <- marb.cov[match(pd$child_id, marb.cov$COI_ID), 'MomSmokedRegularly']
  pd$preg_smoke <- marb.cov[match(pd$child_id, marb.cov$COI_ID), 'SmokeYN_Pregnancy']
  pd$maternal_age <- marb.cov[match(pd$child_id, marb.cov$COI_ID),'MomAgeYr']
  pd$PC1 <- pc[match(pd$child_id, rownames(pc)),1]
  pd$PC2 <- pc[match(pd$child_id, rownames(pc)),2]

  
  pd
}

metals.marbles.T2 <- get_covarsM(metals.marbles, pcv.marbles)
metals.marbles.T3 <- get_covarsM(metals.marbles.last, pcv.marbles.last)

marbles.T2.summ <- metals.marbles.T2 %>% group_by(Analyte.Code) %>%
  summarize(mean=mean(Concentration_sg, na.rm=T), sd=sd(Concentration_sg, na.rm=T), median=median(Concentration_sg, na.rm=T),
            IQR=IQR(Concentration_sg, na.rm=T),  above_lod=sum(Concentration>LOD, na.rm=T), n=n(), pct_over_LOD=round(above_lod/n*100,1)) %>% data.frame()

marbles.T3.summ <- metals.marbles.T3 %>% group_by(Analyte.Code) %>%
  summarize(mean=mean(Concentration_sg, na.rm=T), sd=sd(Concentration_sg, na.rm=T), median=median(Concentration_sg, na.rm=T),
            IQR=IQR(Concentration_sg, na.rm=T),  above_lod=sum(Concentration>LOD, na.rm=T), n=n(), pct_over_LOD=round(above_lod/n*100,1)) %>% data.frame()


### metals descriptives tables

earli.T2.summ <- rounding(earli.T2.summ)
earli.T3.summ <- rounding(earli.T3.summ)
marbles.T2.summ <- rounding(marbles.T2.summ)
marbles.T3.summ <- rounding(marbles.T3.summ)

earli.T2.summ$cohort <- 'EARLI'
earli.T3.summ$cohort <- 'EARLI'
marbles.T2.summ$cohort <- 'MARBLES'
marbles.T3.summ$cohort <- 'MARBLES'


T2.summ <- rbind(earli.T2.summ[,c(1,9,2:8)], marbles.T2.summ[,c(1,9,2:8)])
T3.summ <- rbind(earli.T3.summ[,c(1,9,2:8)], marbles.T3.summ[,c(1,9,2:8)])

T2.summ <- T2.summ[order(T2.summ$Analyte.Code, T2.summ$cohort), ]
T3.summ <- T3.summ[order(T3.summ$Analyte.Code, T3.summ$cohort), ]

write.csv(T2.summ, file=paste0(path,"/Tables/metal_descriptives_T2.csv"), row.names=F, quote=F)
write.csv(T3.summ, file=paste0(path,"/Tables/metal_descriptives_T3.csv"), row.names=F, quote=F)


### descriptive tables
library(compareGroups)

gather_descriptivesM <- function(pd){
  descriptives <- pd[!duplicated(pd$child_id),]
  descriptives <- descriptives[!is.na(descriptives$asd) & !is.na(descriptives$MomEdu &
                              !is.na(descriptives$coi_gender)) & 
                              !is.na(descriptives$maternal_age) &
                              !is.na(descriptives$GA_deliv_wks),]
  
  descriptives$MomEdu <- ifelse(descriptives$MomEdu, "College Degree", "No College Degree")
  descriptives$ever_smoke <- ifelse(is.nan(descriptives$ever_smoke), NA, descriptives$ever_smoke)
  descriptives$ever_smoke <- factor(descriptives$ever_smoke)
  descriptives$preg_smoke <- ifelse(is.nan(descriptives$preg_smoke), NA, descriptives$preg_smoke)
  descriptives$preg_smoke <- factor(descriptives$preg_smoke)
  
  
  restab <- compareGroups(asd ~ MomEdu + coi_gender + maternal_age + GA_deliv_wks + ever_smoke + preg_smoke,
                          data=descriptives)
  createTable(restab)
}

tab.marbles.T2 <- gather_descriptivesM(metals.marbles.T2)
tab.marbles.T3 <- gather_descriptivesM(metals.marbles.T3)

export2word(tab.marbles.T2, file=file.path(path,'Tables/marbles_early_table1.docx'))
export2word(tab.marbles.T3, file=file.path(path,'Tables/marbles_late_table1.docx'))


# ### covariate landscape relationships
# library(reshape2)
# covs <- c('asd','MomEdu','coi_gender','maternal_age','GA_deliv_wks','ever_smoke', 'preg_smoke')
# 
# cov_p(metals.marbles.T2)
# cov_p(metals.marbles.T3)
# 
# 
# 
# ### ASD vs PC
# marbles.pc_asd <- metals.marbles.add %>% filter(Analyte.Code=='Lead')
# ggplot(marbles.pc_asd[marbles.pc_asd$PC1>-20,], aes(x=PC1, y=PC2, col=asd)) +
#   geom_point() + theme_bw()
# glm(asd ~ PC1 + PC2, data=marbles.pc_asd[marbles.pc_asd$asd != 'Non-TD',], family=binomial(link="logit")) %>% summary


### bivariate tests
# lod_percents <- read.csv(file.path(path,"../Metals QC/over_LOD_cohort.csv"))
# lod.marbles <- lod_percents[lod_percents$cohort=='MARBLES',]
# lod.marbles$mod <- ifelse(lod.marbles$pct_over_LOD>70, 'continuous', 'binary')
# mod.type <- lod.marbles$mod
# names(mod.type) <- lod.marbles$Analyte.Code

IQRs.mT2 <- metals.marbles.T2 %>% group_by(Analyte.Code) %>% summarize(IQR(Concentration_sg, na.rm=T)) %>% data.frame
IQRs.mT2 <- IQRs.mT2[,2]
names(IQRs.mT2) <- metals

IQRs.mT3 <- metals.marbles.T3 %>% group_by(Analyte.Code) %>% summarize(IQR(Concentration_sg, na.rm=T)) %>% data.frame
IQRs.mT3 <- IQRs.mT3[,2]
names(IQRs.mT3) <- metals

pdf(file.path(path,"Plots/marbles_firstT_violin.pdf"))
for(met in metals){
  p = ggplot(metals.marbles.T2 %>% filter(Analyte.Code==met), aes(x=factor(asd), y=Concentration_sg)) +
  geom_violin() +geom_jitter(shape=16, position=position_jitter(0.2)) +
    ggtitle(met) + xlab('') +
    theme_bw() +
    theme(axis.text.x=element_text(size=16, face="bold"))
  print(p)
}
dev.off()

```

Early vs Late Preg
```{r}
#remove ones with only single time
table(metals.marbles$SID %in% metals.marbles.last$SID)
only.one <- metals.marbles$SID[metals.marbles$SID %in% metals.marbles.last$SID] %>% unique()

marbles.epreg <- metals.marbles[!metals.marbles$SID %in% only.one, ]
marbles.lpreg <- metals.marbles.last[!metals.marbles.last$SID %in% only.one, ]
dim(marbles.epreg)
dim(marbles.lpreg)

#remove those with no sg
table(is.na(marbles.epreg$sg))
table(is.na(marbles.lpreg$sg))
no.sg <- marbles.epreg$child_id[is.na(marbles.epreg$sg)] %>% unique

marbles.epreg <- marbles.epreg[!marbles.epreg$child_id %in% no.sg, ]
marbles.lpreg <- marbles.lpreg[!marbles.lpreg$child_id %in% no.sg, ]
dim(marbles.epreg)
dim(marbles.lpreg)
identical(marbles.epreg$child_id, marbles.lpreg$child_id)

length(unique(marbles.epreg$child_id))
length(unique(marbles.lpreg$child_id))


cor(marbles.epreg$Con_sg_orig, marbles.lpreg$Con_sg_orig)
time.cors <- sapply(metals, FUN=function(x){
  epreg = marbles.epreg %>% filter(Analyte.Code==x)
  lpreg = marbles.lpreg %>% filter(Analyte.Code==x)
  round(cor(epreg$Con_sg_orig, lpreg$Con_sg_orig, method='spearman'),2)
})
write.csv(time.cors, file.path(path,"marbles_time_cor.csv"))

plot.tm <- function(met){
  m.epreg <- marbles.epreg %>% filter(Analyte.Code==met)
  m.lpreg <- marbles.lpreg %>% filter(Analyte.Code==met)
  dat <- data.frame(epreg=m.epreg$Con_sg_orig, lpreg=m.lpreg$Con_sg_orig)
  
  ggplot(dat, aes(epreg, lpreg)) +
    geom_point() +
    theme_bw() +
    xlab(paste0("Early Pregnancy ",met)) +
    ylab(paste0("Late Pregnancy ",met))
}

plot.tm('Lead')
plot.tm('Mercury')
plot.tm('Cadmium')
```

#model fitting

```{r models}
model_fit_logbin <- function(pd){
  asd.res <- list()
  ntd.res <- list()
  
  for(met in metals){
    sub = pd %>% filter(Analyte.Code==met)
  
    asd = sub %>% filter(asd %in% c('TD','ASD'))
    asd$asd = ifelse(asd$asd=='TD',0,1)
    ntd = sub %>% filter(asd %in% c('TD','Non-TD'))
    ntd$asd = ifelse(ntd$asd=='TD',0,1)

    print(met)
    
    if(mod.type[met] == 'continuous'){
  
      #fit.asd = glm(asd ~ Concentration_sg + MomEdu + coi_gender + maternal_age + GA_deliv_wks, 
      #              data=asd, poisson)
      #fit.ntd = glm(asd ~ Concentration_sg + MomEdu + coi_gender + maternal_age + GA_deliv_wks, 
      #              data=ntd, poisson)
      
      fit.asd = logbin(asd ~ Concentration_sg + MomEdu + coi_gender + maternal_age + GA_deliv_wks, data=asd, bound.tol=1e-20, epsilon=1e-30, maxit=10000000)
      fit.ntd = logbin(asd ~ Concentration_sg + MomEdu + coi_gender + maternal_age + GA_deliv_wks, data=ntd, bound.tol=1e-20, epsilon=1e-30, maxit=10000000)
      
    }else{
      
      asd$overLOD <- asd$Concentration > asd$LOD
      ntd$overLOD <- ntd$Concentration > ntd$LOD
      
      #fit.asd = glm(asd ~ overLOD + MomEdu + coi_gender + maternal_age + GA_deliv_wks, 
      #              data=asd, poisson)
      #fit.ntd = glm(asd ~ overLOD + MomEdu + coi_gender + maternal_age + GA_deliv_wks, 
      #              data=ntd, poisson)
      
      fit.asd = logbin(asd ~ overLOD + MomEdu + coi_gender + maternal_age + GA_deliv_wks, data=asd, bound.tol=1e-20, epsilon=1e-30, maxit=10000000)
      fit.ntd = logbin(asd ~ overLOD + MomEdu + coi_gender + maternal_age + GA_deliv_wks, data=ntd, bound.tol=1e-20, epsilon=1e-30, maxit=10000000)
    }
  
    asd.res[[met]] <- fit.asd
    ntd.res[[met]] <- fit.ntd
  }
  
  return(list(asd=asd.res, ntd=ntd.res))
}


earli.resT2.logbin <- model_fit_logbin(metals.earli.T2)
earli.resT3.logbin <- model_fit_logbin(metals.earli.T3)

marbles.resT2.logbin <- model_fit_logbin(metals.marbles.T2)
marbles.resT3.logbin <- model_fit_logbin(metals.marbles.T3)
```


```{r extract}

extract_res <- function(res, pd, IQRs){
  summ <- pd %>% group_by(Analyte.Code, asd) %>% 
    filter(!is.na(Concentration) & asd %in% c('TD','ASD')) %>%
  summarize(mean=mean(Concentration), 
            sd=sd(Concentration), 
            above_lod=sum(Concentration>LOD),
            n=n(), 
            pct_over_LOD=round(above_lod/n*100,1)) %>%
  data.frame()


  estimates <- sapply(metals, FUN=function(x){
    summary(res[[x]])$coefficients[2,1]
  })
  
  sds <- sapply(metals, FUN=function(x){
    summary(res[[x]])$coefficients[2,2]
  })
  
  pvals <- sapply(metals, FUN=function(x){
    summary(res[[x]])$coefficients[2,4]
  })
  
  fits <- summ %>% group_by(Analyte.Code) %>%
    mutate(model=mod.type[Analyte.Code], 
           estimate=estimates[Analyte.Code],
           se=sds[Analyte.Code],
           pval=pvals[Analyte.Code]) %>% data.frame
  
  fits$lower <- ifelse(fits$model=='binary',
                      round(exp(fits$estimate-1.96*fits$se),2),                                  round(exp(fits$estimate*IQRs[fits$Analyte.Code]-1.96*fits$se*IQRs[fits$Analyte.Code]),4))
  fits$OR <- ifelse(fits$model=='binary',
                      round(exp(fits$estimate),2),
                      round(exp(fits$estimate*IQRs[fits$Analyte.Code]),4))
  fits$upper <- ifelse(fits$model=='binary',
                      round(exp(fits$estimate+1.96*fits$se),2),                               round(exp(fits$estimate*IQRs[fits$Analyte.Code]+1.96*fits$se*IQRs[fits$Analyte.Code]),4))
  
  fits$CI <- paste0(fits$OR, '(', fits$lower, ',', fits$upper,')')
    
  fits$Analyte.Code[seq(2,44,2)] <- NA
  fits$model[seq(2,44,2)] <- NA
  fits$estimate[seq(2,44,2)] <- NA
  fits$se[seq(2,44,2)] <- NA
  fits$pval[seq(2,44,2)] <- NA
  fits$CI[seq(2,44,2)] <- NA
  
  fits
}


earli.asd.T2.poi <- extract_res(earli.resT2.logbin$asd, metals.earli.T2, IQRs.T2)
earli.ntd.T2.poi <- extract_res(earli.resT2.logbin$ntd, metals.earli.T2, IQRs.T2)

earli.asd.T3.poi <- extract_res(earli.resT3.logbin$asd, metals.earli.T3, IQRs.T3)
earli.ntd.T3.poi <- extract_res(earli.resT3.logbin$ntd, metals.earli.T3, IQRs.T3)

marbles.asd.T2.poi <- extract_res(marbles.resT2.logbin$asd, metals.marbles.T2, IQRs.mT2)
marbles.ntd.T2.poi <- extract_res(marbles.resT2.logbin$ntd, metals.marbles.T2, IQRs.mT2)

marbles.asd.T3.poi <- extract_res(marbles.resT3.logbin$asd, metals.marbles.T3, IQRs.mT3)
marbles.ntd.T3.poi <- extract_res(marbles.resT3.logbin$ntd, metals.marbles.T3, IQRs.mT3)
```



# forest plot
```{r forest}

process_res <- function(res, cohort, IQR){
  pro <- res[!is.na(res$Analyte.Code), c('Analyte.Code','model','lower','OR','upper','CI','pval', 'estimate', 'se')]
  pro <- pro %>% filter(!Analyte.Code %in% c('Beryllium','Platinum','Tungsten','Uranium','Vanadium'))
  pro$cohort <- cohort
  
  IQR <- IQR[pro$Analyte.Code]
  pro$estimate <- ifelse(pro$Analyte.Code %in% c('Antimony', 'Cadmium', 'Chromium', 'Lead'),
                         pro$estimate,
                         pro$estimate * IQR[pro$Analyte.Code])
  pro$se <- ifelse(pro$Analyte.Code %in% c('Antimony', 'Cadmium', 'Chromium', 'Lead'),
                         pro$se,
                         pro$se * IQR[pro$Analyte.Code])
  
  pro
}

# #logistic reg
# res.earli.T2.asd <- process_res(earli.asd.T2, "EARLI", IQRs.T2)
# res.earli.T2.ntd <- process_res(earli.ntd.T2, "EARLI", IQRs.T2)
# 
# res.earli.T3.asd <- process_res(earli.asd.T3, "EARLI", IQRs.T3)
# res.earli.T3.ntd <- process_res(earli.ntd.T3, "EARLI", IQRs.T3)
# 
# res.marbles.T2.asd <- process_res(marbles.asd.T2, "MARBLES", IQRs.mT2)
# res.marbles.T2.ntd <- process_res(marbles.ntd.T2, "MARBLES", IQRs.mT2)
# 
# res.marbles.T3.asd <- process_res(marbles.asd.T3, "MARBLES", IQRs.mT3)
# res.marbles.T3.ntd <- process_res(marbles.ntd.T3, "MARBLES", IQRs.mT3)

#poisson
res.earli.T2.asd.poi <- process_res(earli.asd.T2.poi, "EARLI", IQRs.T2)
res.earli.T2.ntd.poi <- process_res(earli.ntd.T2.poi, "EARLI", IQRs.T2)

res.earli.T3.asd.poi <- process_res(earli.asd.T3.poi, "EARLI", IQRs.T3)
res.earli.T3.ntd.poi <- process_res(earli.ntd.T3.poi, "EARLI", IQRs.T3)

res.marbles.T2.asd.poi <- process_res(marbles.asd.T2.poi, "MARBLES", IQRs.mT2)
res.marbles.T2.ntd.poi <- process_res(marbles.ntd.T2.poi, "MARBLES", IQRs.mT2)

res.marbles.T3.asd.poi <- process_res(marbles.asd.T3.poi, "MARBLES", IQRs.mT3)
res.marbles.T3.ntd.poi <- process_res(marbles.ntd.T3.poi, "MARBLES", IQRs.mT3)


### group time/outcome 
binding <- function(res1, res2){
  res.bind <- rbind(res1, res2)
  res.bind$Analyte.Code <- factor(res.bind$Analyte.Code)
  res.bind$Analyte.Code <- factor(res.bind$Analyte.Code, levels=rev(levels(res.bind$Analyte.Code)))
  
  res.bind
}

# res.asdT2 <- binding(res.earli.T2.asd, res.marbles.T2.asd)
# res.asdT3 <- binding(res.earli.T3.asd, res.marbles.T3.asd)
# res.ntdT2 <- binding(res.earli.T2.ntd, res.marbles.T2.ntd)
# res.ntdT3 <- binding(res.earli.T3.ntd, res.marbles.T3.ntd)
# 
# save(res.asdT2, res.asdT3, res.ntdT2, res.ntdT3,
#      file=paste0(path,'/Data/results.RDA'))

res.asdT2.poi <- binding(res.earli.T2.asd.poi, res.marbles.T2.asd.poi)
res.asdT3.poi <- binding(res.earli.T3.asd.poi, res.marbles.T3.asd.poi)
res.ntdT2.poi <- binding(res.earli.T2.ntd.poi, res.marbles.T2.ntd.poi)
res.ntdT3.poi <- binding(res.earli.T3.ntd.poi, res.marbles.T3.ntd.poi)

save(res.asdT2.poi, res.asdT3.poi, res.ntdT2.poi, res.ntdT3.poi,
     file=file.path(path,'Data/logbin_results.RDA'))


plot_bin_con <- function(res, what){
  forest.bin <- ggplot(data=res%>%filter(model=='binary'), 
                       aes(x=Analyte.Code, y=OR, ymin=lower, ymax=upper)) +
    geom_pointrange(aes(col=Analyte.Code), position=position_dodge2(width=1), size=1.3) +
    geom_hline(yintercept=1, linetype=2) +
    facet_wrap(~cohort) +
    theme_bw() +
    theme(text = element_text(size=20),
          legend.position = 'none') +
    xlab('') + ylab('Odds Ratio') +
    coord_flip()

  forest.con <- ggplot(data=res%>%filter(model=='continuous'), 
                       aes(x=Analyte.Code, y=OR, ymin=lower, ymax=upper)) +
    geom_pointrange(aes(col=Analyte.Code), position=position_dodge2(width=1), size=1.3) +
    geom_hline(yintercept=1, linetype=2) +
    facet_wrap(~cohort) +
    theme_bw() +
    theme(text = element_text(size=20),
          legend.position = 'none') +
    xlab('') + ylab('Odds Ratio') +
    coord_flip()
  
  ggsave(forest.bin, file=paste0(path,'Plots/forest_bin_',what,'.svg'),height=4, width=10)
  ggsave(forest.con, file=paste0(path,'Plots/forest_con_',what,'.svg'),height=9, width=10)
    
  invisible()
}

plot_bin_con(res.asdT2, 'asdT2')
plot_bin_con(res.asdT3, 'asdT3')

plot_bin_con(res.ntdT2, 'ntdT2')
plot_bin_con(res.ntdT3, 'ntdT3')




#when running with everything continuous
get_alt <- function(res,what){
  results.bin.alt <- res[res$Analyte.Code %in% c('Antimony', "Cadmium", "Chromium", "Lead"),]
  forest.bin.alt <- ggplot(data=results.bin.alt, aes(x=Analyte.Code, y=OR, ymin=lower, ymax=upper)) +
    geom_pointrange(aes(col=Analyte.Code), position=position_dodge2(width=1), size=1.3) +
    geom_hline(yintercept=1, linetype=2) +
    facet_wrap(~cohort) +
    theme_bw() +
    theme(text = element_text(size=20),
          legend.position = 'none') +
    xlab('') + ylab('Odds Ratio') +
    coord_flip()
  ggsave(forest.bin.alt, file=paste0(path,'Plots/forest_con_alt_',what,'.svg'),height=4, width=10)

}

get_alt(res.asdT2, 'asdT2')
get_alt(res.asdT3, 'asdT3')

get_alt(res.ntdT2, 'ntdT2')
get_alt(res.ntdT3, 'ntdT3')

results.bin.alt <- results[results$Analyte.Code %in% c('Antimony', "Cadmium", "Chromium", "Lead"),]
forest.bin.alt <- ggplot(data=results.bin.alt, aes(x=Analyte.Code, y=OR, ymin=lower, ymax=upper)) +
  geom_pointrange(aes(col=Analyte.Code), position=position_dodge2(width=1), size=1.3) +
  geom_hline(yintercept=1, linetype=2) +
  facet_wrap(~cohort) +
  theme_bw() +
  theme(text = element_text(size=20),
        legend.position = 'none') +
  xlab('') + ylab('Odds Ratio') +
  coord_flip()
ggsave(forest.bin.alt, file=file.path(path,'Plots/forest_bin_alt.svg'),height=4, width=10)

results.bin.alt2 <- results2[results2$Analyte.Code %in% c('Antimony', "Cadmium", "Chromium", "Lead"),]
forest.bin.alt2 <- ggplot(data=results.bin.alt2, aes(x=Analyte.Code, y=OR, ymin=lower, ymax=upper)) +
  geom_pointrange(aes(col=Analyte.Code), position=position_dodge2(width=1), size=1.3) +
  geom_hline(yintercept=1, linetype=2) +
  facet_wrap(~cohort) +
  theme_bw() +
  theme(text = element_text(size=20),
        legend.position = 'none') +
  xlab('') + ylab('Odds Ratio') +
  coord_flip()
ggsave(forest.bin.alt2, file=file.path(path,'Plots/forest_bin_alt2.svg'),height=4, width=10)


```

### Examine EARLI maternal blood relations
```{r earli blood}
matblood <- read.csv("F:/Drive/CDC_Measures/ndar_blood_metals.csv", skip=1)
matblood$fam <- substr(matblood$src_subject_id,1,5)

pd <- metals.earli.T2 %>% filter(Analyte.Code=="Cadmium")
table(pd$fam %in% matblood$fam)
table(matblood$fam %in% pd$fam)

pd$cd_bl <- matblood[match(pd$fam, matblood$fam), "bcd"]
pd$cd_lod <- matblood[match(pd$fam, matblood$fam), "bcd_below_lod"]

pd$pb_bl <- matblood[match(pd$fam, matblood$fam), "bpb"]
pd$pb_lod <- matblood[match(pd$fam, matblood$fam), "bpb_below_lod"]

pd$mn_bl <- matblood[match(pd$fam, matblood$fam), "bmn"]
pd$mn_lod <- matblood[match(pd$fam, matblood$fam), "bmn_below_lod"]

pd$se_bl <- matblood[match(pd$fam, matblood$fam), "bse"]
pd$se_lod <- matblood[match(pd$fam, matblood$fam), "bse_below_lod"]

pd$thg_bl <- matblood[match(pd$fam, matblood$fam), "thg"]
pd$thg_lod <- matblood[match(pd$fam, matblood$fam), "thg_below_lod"]

table(pd$cd_bl)
table(pd$cd_lod)

table(pd$pb_bl)
table(pd$pb_lod)

table(pd$mn_bl)
table(pd$mn_lod)

table(pd$se_bl)
table(pd$se_lod)

table(pd$thg_bl)
table(pd$thg_lod)

pd$cd_bl <- ifelse(pd$cd_lod==1, 0.1/sqrt(2), pd$cd_bl)
pd$cd_bl <- ifelse(pd$cd_bl<0, NA, pd$cd_bl)

pd$pb_bl <- ifelse(pd$pb_bl<0, NA, pd$pb_bl)
pd$mn_bl <- ifelse(pd$mn_bl<0, NA, pd$mn_bl)
pd$se_bl <- ifelse(pd$se_bl<0, NA, pd$se_bl)

pd$thg_bl <- ifelse(pd$thg_lod==1, 0.28/sqrt(2), pd$thg_bl)
pd$thg_bl <- ifelse(pd$thg_bl<0, NA, pd$thg_bl)


### descriptive table

blood.descriptives <- pd[!is.na(pd$cd_bl) & !is.na(pd$asd) & !is.na(pd$MomEdu &
                              !is.na(pd$coi_gender)) & !is.na(pd$maternal_age)
                              & !is.na(pd$GA_deliv_wks),]
  
  
blood.descriptives$MomEdu <- ifelse(blood.descriptives$MomEdu, "College Degree", "No College Degree")
  
blood.restab <- compareGroups(asd ~ MomEdu + maternal_age + coi_gender + GA_deliv_wks,
                        data=blood.descriptives)
blood.word <- createTable(blood.restab)
export2word(blood.word, file=file.path(path,'Tables/EARLI_blood_desc_tab.docx'))


### fit models


pd.asd = blood.descriptives %>% filter(asd %in% c('TD','ASD'))
pd.asd$asd = factor(pd.asd$asd)
pd.asd$coi_gender <- factor(pd.asd$coi_gender)
pd.ntd = blood.descriptives %>% filter(asd %in% c('TD','Non-TD'))
pd.ntd$asd = factor(pd.ntd$asd)




tapply(pd.asd$cd_bl, pd.asd$asd, mean, na.rm=T)
tapply(pd.ntd$cd_bl, pd.ntd$asd, mean, na.rm=T)

table(pd.asd$asd, !is.na(pd.asd$cd_bl))
table(pd.ntd$asd, !is.na(pd.ntd$cd_bl))

table(pd.asd$asd, !is.na(pd.asd$mn_bl))
table(pd.ntd$asd, !is.na(pd.ntd$mn_bl))

cd.glm = glm(asd ~ cd_bl + MomEdu + coi_gender + maternal_age + GA_deliv_wks, data=pd.asd, family=binomial(link="logit"))
# blood.ntd = glm(asd ~ cd_bl + MomEdu + coi_gender + maternal_age + GA_deliv_wks, data=pd.ntd, family=binomial(link="logit"))

cd.glml = glm(asd ~ cd_bl + coi_gender + maternal_age + GA_deliv_wks, data=pd.asd, family=binomial(link="log"), maxit=10000000, start=c(log()))

cd.logbin = logbin(asd ~ cd_bl + MomEdu + coi_gender, data=pd.asd, maxit=10000000)

cd.logbin = logbin(asd ~ cd_bl + MomEdu + coi_gender + maternal_age + GA_deliv_wks, data=pd.asd, bound.tol=1e-20, epsilon=1e-30, maxit=10000000)

cd.glm = glm(asd ~ cd_bl + MomEdu + coi_gender + maternal_age + GA_deliv_wks, data=pd.asd, family=binomial)
cd.logbin = probratio(cd.glm, scale='log', method='delta')


fit.ntd = logbin(asd ~ cd_bl + MomEdu + coi_gender + maternal_age + GA_deliv_wks, data=pd.ntd, bound.tol=1e-20, epsilon=1e-30, maxit=10000000)

### fit models

bl.metals <- list(cd="cd_bl", pb="pb_bl", mn="mn_bl", se="se_bl", thg="thg_bl")

blood.asd <- lapply(bl.metals, FUN=function(x){
  # logbin(paste0('asd ~ ', x, ' + MomEdu + coi_gender + maternal_age + GA_deliv_wks') %>% formula(), 
  #     data=pd.asd, bound.tol=1e-20, epsilon=1e-30, maxit=10000000) %>%
  #   summary()
  mod.glm = glm(paste0('asd ~ ', x, ' + MomEdu + coi_gender + maternal_age + GA_deliv_wks') 
                %>% formula(), 
               data=pd.asd, family=binomial)
  probratio(mod.glm, scale='log', method='delta')
})

blood.ntd <- lapply(bl.metals, FUN=function(x){
  # logbin(paste0('asd ~ ', x, ' + MomEdu + coi_gender + maternal_age + GA_deliv_wks') %>% formula(), 
  #     data=pd.ntd, bound.tol=1e-20, epsilon=1e-30, maxit=10000000) %>%
  #   summary()
  mod.glm = glm(paste0('asd ~ ', x, ' + MomEdu + coi_gender + maternal_age + GA_deliv_wks') 
                %>% formula(), 
               data=pd.ntd, family=binomial)
  probratio(mod.glm, scale='log', method='delta')
})

### forest plot

blood.asd.CI <- data.frame(metals=c('Cadmium', 'Lead', 'Manganese', 'Selenium', 'Total Mercury'))
blood.ntd.CI <- data.frame(metals=c('Cadmium', 'Lead', 'Manganese', 'Selenium', 'Total Mercury'))

grab_values <- function(summ){
  blood.IQR = sapply(bl.metals, FUN=function(x){
    IQR(pd[,x], na.rm=T)
  })
  
  OR = lapply(summ, FUN=function(x){x[1,1]}) %>% unlist
  err = lapply(summ, FUN=function(x){x[1,2]}) %>% unlist
  OR = OR * blood.IQR
  lower = OR - 1.96*blood.IQR*err
  upper = OR + 1.96*blood.IQR*err
  
  OR = OR %>% exp %>% round(2)
  lower = lower %>% exp %>% round(2)
  upper = upper %>% exp %>% round(2)
  
  values = data.frame(OR=OR, lower=lower, upper=upper)
  values
}

blood.asd.CI <- cbind(blood.asd.CI, grab_values(blood.asd))
blood.ntd.CI <- cbind(blood.ntd.CI, grab_values(blood.ntd))

forest.blood.asd <- ggplot(data=blood.asd.CI, aes(x=metals, y=OR, ymin=lower, ymax=upper)) +
  geom_pointrange(aes(col=metals), position=position_dodge2(width=1), size=1.3) +
  geom_hline(yintercept=1, linetype=2) +
  theme_bw() +
  theme(text = element_text(size=20),
        legend.position = 'none') +
  xlab('') + ylab('Odds Ratio') +
  coord_flip()

forest.blood.ntd <- ggplot(data=blood.ntd.CI, aes(x=metals, y=OR, ymin=lower, ymax=upper)) +
  geom_pointrange(aes(col=metals), position=position_dodge2(width=1), size=1.3) +
  geom_hline(yintercept=1, linetype=2) +
  theme_bw() +
  theme(text = element_text(size=20),
        legend.position = 'none') +
  xlab('') + ylab('Odds Ratio') +
  coord_flip()

forest.blood.asd
forest.blood.ntd


ggplot(pd.asd, aes(x=asd, y=cd_bl)) +
  geom_boxplot()
ggplot(pd.ntd, aes(x=asd, y=cd_bl)) +
  geom_boxplot()
```



Meta Analysis
```{r}
library(dplyr)
library(meta)
library(ggplot2)
library(gridExtra)
library(openxlsx)
path <- 'F:/Drive/Urine_Metals/Metals ASD'

#estimates and SE already scaled by IQR of cohorts
#load(file=paste0(path,'/Data/results.RDA'))
load(file=paste0(path,'Data/logbin_results.RDA'))
#load(file=paste0(path,'Data/poisson_results.RDA'))

res.asdT2 <- res.asdT2.poi
res.asdT3 <- res.asdT3.poi
res.ntdT2 <- res.ntdT2.poi
res.ntdT3 <- res.ntdT3.poi

metals <- unique(res.asdT2$Analyte.Code) %>% as.character

meta <- function(res){
  met.res = lapply(metals, FUN=function(x){
    results = res[res$Analyte.Code==x, ]
    metagen(estimate,
        se,
        data=results,
        studlab=results$cohort,
        comb.fixed = TRUE,
        comb.random = FALSE,
        prediction=TRUE,
        sm="OR")
  })
  names(met.res) <- metals
  met.res
}

meta.asdT2 <- meta(res.asdT2)
meta.asdT3 <- meta(res.asdT3)
meta.ntdT2 <- meta(res.ntdT2)
meta.ntdT3 <- meta(res.ntdT3)

  

### format for forest plot

meta.forest <- function(meta.res){
  lapply(metals, FUN=function(x){
    res = meta.res[[x]]
    
    coefs = data.frame(metal=x,
               lab=c('Meta','EARLI','MARBLES'),
               effect=c(res$TE.fixed, res$TE[1], res$TE[2]),
               lower=c(res$lower.fixed, res$lower[1], res$lower[2]),
               upper=c(res$upper.fixed, res$upper[1], res$upper[2]))
    
    coefs$lab = factor(coefs$lab, levels=c('Meta','EARLI','MARBLES'))
    
    coefs$OR = exp(coefs$effect)
    coefs$OR.lower = exp(coefs$lower)
    coefs$OR.upper = exp(coefs$upper)
    
    coefs$alpha = I(ifelse(coefs$lab=='Meta', 1.0, ifelse(coefs$lab=='EARLI',0.4, 0.2)))
    
    coefs$shape = I(ifelse(coefs$lab=='Meta', 18, 16))
    
    coefs$metal = ifelse(res$pval.fixed < 0.05, paste0(coefs$metal,'*'), coefs$metal)
    
    coefs
  })
}

coefs.asdT2 <- meta.forest(meta.asdT2) %>% bind_rows()
coefs.asdT3 <- meta.forest(meta.asdT3) %>% bind_rows()
coefs.ntdT2 <- meta.forest(meta.ntdT2) %>% bind_rows()
coefs.ntdT3 <- meta.forest(meta.ntdT3) %>% bind_rows()

metals.c <- metals[!metals %in% c('Antimony', "Cadmium", "Chromium", "Lead")]
metals.c1 <- metals.c[1:7]
metals.c2 <- metals.c[8:13]
metals.b <- c('Antimony', "Cadmium", "Chromium", "Lead")




meta_plots <-function(coefs, what){
  forest.bin <- ggplot(data=coefs[grepl(paste(metals.b, collapse='|'), coefs.asdT2$metal),], 
                       aes(x=lab, y=OR, ymin=OR.lower, ymax=OR.upper, alpha=alpha, shape=shape)) +
    geom_pointrange(position=position_dodge2(width=1), size=1.3) +
    geom_hline(yintercept=1, linetype=2) +
    theme_bw() + facet_grid(metal ~.) +
    theme(text = element_text(size=20), strip.text.y = element_text(angle=0)) +
    xlab('') + ylab('Risk Ratio') +
    coord_flip()
  
    forest.con1 <- ggplot(data=coefs[grepl(paste(metals.c1, collapse='|'), coefs.asdT2$metal),], 
                       aes(x=lab, y=OR, ymin=OR.lower, ymax=OR.upper, alpha=alpha, shape=shape)) +
    geom_pointrange(position=position_dodge2(width=1), size=1.3) +
    geom_hline(yintercept=1, linetype=2) +
    theme_bw() + facet_grid(metal ~.) +
    theme(text = element_text(size=20), strip.text.y = element_text(angle=0), 
          legend.position = 'none') +
    xlab('') + ylab('Risk Ratio') +
    coord_flip()
    
    forest.con2 <- ggplot(data=coefs[grepl(paste(metals.c2, collapse='|'), coefs.asdT2$metal),], 
                       aes(x=lab, y=OR, ymin=OR.lower, ymax=OR.upper, alpha=alpha, shape=shape)) +
    geom_pointrange(position=position_dodge2(width=1), size=1.3) +
    geom_hline(yintercept=1, linetype=2) +
    theme_bw() + facet_grid(metal ~.) +
    theme(text = element_text(size=20), strip.text.y = element_text(angle=0),
          legend.position = 'none') +
    xlab('') + ylab('Risk Ratio') +
    coord_flip()

  #ggsave(forest.bin, file=paste0(path,'/Plots/meta/forest_meta_bin_',what,'.svg'),height=4, width=10)
  #ggsave(forest.con1, file=paste0(path,'/Plots/meta/forest_meta_con1_',what,'.svg'),height=9, width=10)
  #ggsave(forest.con2, file=paste0(path,'/Plots/meta/forest_meta_con2_',what,'.svg'),height=9, width=10)
  
  combi.plot = grid.arrange(forest.bin, forest.con1, forest.con2,
                            heights=c(1,2),
                            layout_matrix = rbind(c(4,1,1,4),
                                                  c(2,2,3,3)))
  
  ggsave(combi.plot, file=paste0(path,'/Plots/meta/forest_',what,'.svg'),height=10, width=16)
}


meta_plots(coefs.asdT2, 'asdT2')
meta_plots(coefs.asdT3, 'asdT3')
meta_plots(coefs.ntdT2, 'ntdT2')
meta_plots(coefs.ntdT3, 'ntdT3')



### big table of all results

meta.res.tab <- function(res){
  metals <- names(res)
  
  EARLI = lapply(res, FUN=function(x){
    tab = data.frame(OR = exp(x$TE[1]) %>% round(2))
    tab$CI = paste0('(',exp(x$TE[1]-1.96*x$seTE[1]) %>% round(2),',',exp(x$TE[1]+1.96*x$seTE[1]) %>% round(2),')')
    tab$p = x$pval[1] %>% signif(2)
    tab
  })
  EARLI = bind_rows(EARLI)
  EARLI = cbind(metals, EARLI)
  
  MARBLES = lapply(res, FUN=function(x){
    tab = data.frame(OR = exp(x$TE[2]) %>% round(2))
    tab$CI = paste0('(',exp(x$TE[2]-1.96*x$seTE[2]) %>% round(2),',',exp(x$TE[2]+1.96*x$seTE[2]) %>% round(2),')')
    tab$p = x$pval[2] %>% signif(2)
    tab
  })
  MARBLES = bind_rows(MARBLES)
  MARBLES = cbind(metals, MARBLES)
  
  meta = lapply(res, FUN=function(x){
    tab = data.frame(OR = exp(x$TE.fixed) %>% round(2))
    tab$CI = paste0('(',exp(x$TE.fixed-1.96*x$seTE.fixed) %>% round(2),',',exp(x$TE.fixed+1.96*x$seTE.fixed) %>% round(2),')')
    tab$p = x$pval.fixed %>% signif(2)
    tab
  }) 
  meta = bind_rows(meta)
  meta = cbind(metals, meta)
  
  tabs = list(EARLI=EARLI, MARBLES=MARBLES, meta=meta)
  
  combi = bind_cols(tabs)
  combi = combi[,-c(5,9)]
  
  combi[match(c(metals.b, metals.c), combi[,1]),]
  
}

tab.asdT2 <- meta.res.tab(meta.asdT2)
tab.asdT3 <- meta.res.tab(meta.asdT3)
tab.ntdT2 <- meta.res.tab(meta.ntdT2)
tab.ntdT3 <- meta.res.tab(meta.ntdT3)


compiled.tab <- list(asdT2=tab.asdT2, asdT3=tab.asdT3, ntdT2=tab.ntdT2, ntdT3=tab.ntdT3)

write.xlsx(compiled.tab, file=paste0(path,'/Tables/meta_estimates_logbin_tables.xlsx'))
```
